[colors.bright]
black = "0x555555"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xffffff"
yellow = "0xf4f99d"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbbbbbb"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[cursor.style]
blinking = "Always"
shape = "Block"

#[font]
#size = 12.0

#[font.bold]
#family = "JetBrainsMono Nerd Font"
#style = "Bold"

#[font.italic]
#family = "JetBrainsMono Nerd Font"
#style = "Italic"

#[font.normal]
#family = "JetBrainsMono Nerd Font"
#style = "Regular"

[scrolling]
history = 10000

[window]
decorations = "none"

[window.padding]
x = 10
y = 15
